name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create mkdocs.yml
        run: |
          echo "site_name: RedClouds Documentation" > mkdocs.yml
          echo "theme:" >> mkdocs.yml
          echo "  name: material" >> mkdocs.yml
          echo "  palette:" >> mkdocs.yml
          echo "    primary: red" >> mkdocs.yml
          echo "    accent: blue" >> mkdocs.yml
          echo "nav:" >> mkdocs.yml
          echo "  - Home: index.md" >> mkdocs.yml
          echo "  - Contributing: CONTRIBUTING.md" >> mkdocs.yml
          echo "  - Code of Conduct: CODE_OF_CONDUCT.md" >> mkdocs.yml
          echo "  - Changelog: ../CHANGELOG.md" >> mkdocs.yml

      - name: Create index.md
        run: |
          cp README.md docs/index.md

      - name: Build documentation
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 